### PR TITLE
RSSOwl update 2.4.0-beta

### PR DESCRIPTION
**Pull request by Xyrio**
for small changes list see https://github.com/Xyrio/RSSOwl

### CODE REVIEW

**Comment by genodeftest** [comment]
@bpasero Can I have your opinion on these changes, please?

**Comment by Xyrio** [comment]
btw temporary removing lines only containing @Override with search and replace in java files, should leave much fewer lines to review.

**Comment by bpasero** [comment]
Thanks, but I am not considering RSSOwl to be active anymore. I will not have the time to review PRs. I think at this time the best approach would be to fork RSSOwl and publish it under a different name with the changes you anticipate. The license should give you all the freedom to do that.

**Comment by genodeftest** [comment]
@bpasero: How about adding Xyrio to the RSSOwl github group, as I suggested via email? That would save Xyrio a lot of work getting everyone to use the "fork".

**Comment by bpasero** [comment]
@genodeftest I am not sure I understand the purpose of adding him to this GitHub repo? To be honest, this GH repo does not have any purpose for RSSOwl and I should probably delete it. I only added the sources here to have an alternative to SourceForge, but I never thought about accepting PRs or issues (and it looks like I cannot disable PRs for this project here).

**Comment by war59312** [comment]
I suggest since you really don't want to support anymore to add link in readme to https://github.com/Xyrio/RSSOwl

and make this repo read only

**Pull request closed without merging**
